/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /**
     * Root
     * @description Root endpoint with API information
     */
    get: operations["root__get"];
  };
  "/chat": {
    /**
     * Chat
     * @description Non-streaming chat endpoint.
     *
     * Processes a user message and returns the complete response.
     *
     * Args:
     *     request: ChatRequest with message and thread_id
     *
     * Returns:
     *     ChatResponse with agent's answer
     *
     * Raises:
     *     HTTPException: If graph execution fails
     */
    post: operations["chat_chat_post"];
  };
  "/chat/stream": {
    /**
     * Chat Stream
     * @description Streaming chat endpoint using Server-Sent Events (SSE).
     *
     * Streams tokens and events in real-time as the agent processes the request.
     *
     * Args:
     *     request: ChatRequest with message and thread_id
     *
     * Returns:
     *     StreamingResponse with SSE events
     */
    post: operations["chat_stream_chat_stream_post"];
  };
  "/history/{thread_id}": {
    /**
     * Get History
     * @description Get conversation history for a thread.
     *
     * Retrieves all checkpoints and messages for the specified thread.
     *
     * Args:
     *     thread_id: Thread identifier
     *
     * Returns:
     *     HistoryResponse with conversation history
     *
     * Raises:
     *     HTTPException: If history retrieval fails
     */
    get: operations["get_history_history__thread_id__get"];
  };
  "/health": {
    /**
     * Health Check
     * @description Health check endpoint
     */
    get: operations["health_check_health_get"];
  };
  "/threads": {
    /**
     * List Threads
     * @description List all chat threads, most recent first
     */
    get: operations["list_threads_threads_get"];
    /**
     * Create Thread
     * @description Create a new chat thread
     */
    post: operations["create_thread_threads_post"];
    /**
     * Delete All Threads
     * @description Delete all chat threads and messages
     */
    delete: operations["delete_all_threads_threads_delete"];
  };
  "/threads/{thread_id}": {
    /**
     * Delete Thread
     * @description Delete a chat thread and all its messages
     */
    delete: operations["delete_thread_threads__thread_id__delete"];
    /**
     * Update Thread
     * @description Update a chat thread's metadata
     */
    patch: operations["update_thread_threads__thread_id__patch"];
  };
  "/threads/{thread_id}/messages": {
    /**
     * List Messages
     * @description List all messages for a thread, ordered by creation time
     */
    get: operations["list_messages_threads__thread_id__messages_get"];
    /**
     * Save Message
     * @description Save a new message to a thread
     */
    post: operations["save_message_threads__thread_id__messages_post"];
  };
  "/threads/{thread_id}/messages/{message_id}": {
    /**
     * Update Message
     * @description Update an existing message (e.g., after streaming completes)
     */
    patch: operations["update_message_threads__thread_id__messages__message_id__patch"];
  };
  "/threads/import": {
    /**
     * Bulk Import
     * @description Import threads and messages from localStorage in bulk
     */
    post: operations["bulk_import_threads_import_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * BulkImportRequest
     * @description Request model for importing threads and messages from localStorage
     */
    BulkImportRequest: {
      /** Threads */
      threads: components["schemas"]["CreateThreadRequest"][];
      /**
       * Messages
       * @description Map of thread_id to list of messages
       */
      messages?: {
        [key: string]: components["schemas"]["SaveMessageRequest"][];
      };
    };
    /**
     * ChatMessageModel
     * @description A single chat message
     */
    ChatMessageModel: {
      /** Id */
      id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /** Timestamp */
      timestamp: string;
      /** Status */
      status?: string | null;
      /** Queries */
      queries?: {
          [key: string]: unknown;
        }[] | null;
      /** Overall Summary */
      overall_summary?: string | null;
    };
    /**
     * ChatRequest
     * @description Request model for chat endpoints
     */
    ChatRequest: {
      /**
       * Message
       * @description User's question or message
       */
      message: string;
      /**
       * Thread Id
       * @description Thread ID for conversation continuity
       */
      thread_id: string;
      /**
       * Anticipate Complexity
       * @description Whether to use more thorough/exploratory analysis (True) or direct answers (False)
       * @default false
       */
      anticipate_complexity?: boolean;
    };
    /**
     * ChatResponse
     * @description Response model for non-streaming chat endpoint
     */
    ChatResponse: {
      /**
       * Response
       * @description Agent's response
       */
      response: string;
      /**
       * Thread Id
       * @description Thread ID for this conversation
       */
      thread_id: string;
      /**
       * Executed Queries
       * @description SQL queries executed with explanations and summaries
       */
      executed_queries?: components["schemas"]["QueryExecutionResponse"][];
    };
    /**
     * CheckpointData
     * @description Single checkpoint in conversation history
     */
    CheckpointData: {
      /**
       * Checkpoint Id
       * @description Unique checkpoint identifier
       */
      checkpoint_id: string;
      /**
       * Messages
       * @description Messages in this checkpoint
       */
      messages?: components["schemas"]["MessageHistory"][];
      /**
       * Timestamp
       * @description ISO timestamp when checkpoint was created
       */
      timestamp?: string | null;
      /**
       * Metadata
       * @description Additional checkpoint metadata
       */
      metadata?: {
        [key: string]: unknown;
      };
    };
    /**
     * CreateThreadRequest
     * @description Request model for creating a thread
     */
    CreateThreadRequest: {
      /**
       * Id
       * @description UUID for the new thread
       */
      id: string;
      /**
       * Title
       * @description Thread title
       * @default New Chat
       */
      title?: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HistoryResponse
     * @description Response model for history endpoint
     */
    HistoryResponse: {
      /**
       * Thread Id
       * @description Thread ID
       */
      thread_id: string;
      /**
       * History
       * @description List of checkpoint states with messages
       */
      history?: components["schemas"]["CheckpointData"][];
    };
    /**
     * MessageHistory
     * @description Single message in conversation history
     */
    MessageHistory: {
      /**
       * Type
       * @description Message type (HumanMessage, AIMessage, etc.)
       */
      type: string;
      /**
       * Content
       * @description Message content
       */
      content: string;
    };
    /**
     * QueryExecutionResponse
     * @description Response model for query execution details
     */
    QueryExecutionResponse: {
      /**
       * Query
       * @description The SQL query that was executed
       */
      query: string;
      /**
       * Explanation
       * @description Human-readable explanation of what the query does
       */
      explanation: string;
      /**
       * Result Summary
       * @description Brief summary of the query results
       */
      result_summary: string;
    };
    /**
     * SaveMessageRequest
     * @description Request model for saving a message
     */
    SaveMessageRequest: {
      /** Id */
      id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /** Timestamp */
      timestamp: string;
      /** Status */
      status?: string | null;
      /** Queries */
      queries?: {
          [key: string]: unknown;
        }[] | null;
      /** Overall Summary */
      overall_summary?: string | null;
    };
    /**
     * ThreadListResponse
     * @description Response model for list of threads
     */
    ThreadListResponse: {
      /** Threads */
      threads: components["schemas"]["ThreadResponse"][];
    };
    /**
     * ThreadResponse
     * @description Response model for a chat thread
     */
    ThreadResponse: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Last Message */
      last_message: string;
      /** Timestamp */
      timestamp: string;
      /** Message Count */
      message_count: number;
    };
    /**
     * UpdateMessageRequest
     * @description Request model for updating a message
     */
    UpdateMessageRequest: {
      /** Content */
      content?: string | null;
      /** Status */
      status?: string | null;
      /** Queries */
      queries?: {
          [key: string]: unknown;
        }[] | null;
      /** Overall Summary */
      overall_summary?: string | null;
    };
    /**
     * UpdateThreadRequest
     * @description Request model for updating a thread
     */
    UpdateThreadRequest: {
      /** Title */
      title?: string | null;
      /** Last Message */
      last_message?: string | null;
      /** Message Count */
      message_count?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Root
   * @description Root endpoint with API information
   */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Chat
   * @description Non-streaming chat endpoint.
   *
   * Processes a user message and returns the complete response.
   *
   * Args:
   *     request: ChatRequest with message and thread_id
   *
   * Returns:
   *     ChatResponse with agent's answer
   *
   * Raises:
   *     HTTPException: If graph execution fails
   */
  chat_chat_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Chat Stream
   * @description Streaming chat endpoint using Server-Sent Events (SSE).
   *
   * Streams tokens and events in real-time as the agent processes the request.
   *
   * Args:
   *     request: ChatRequest with message and thread_id
   *
   * Returns:
   *     StreamingResponse with SSE events
   */
  chat_stream_chat_stream_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get History
   * @description Get conversation history for a thread.
   *
   * Retrieves all checkpoints and messages for the specified thread.
   *
   * Args:
   *     thread_id: Thread identifier
   *
   * Returns:
   *     HistoryResponse with conversation history
   *
   * Raises:
   *     HTTPException: If history retrieval fails
   */
  get_history_history__thread_id__get: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health Check
   * @description Health check endpoint
   */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Threads
   * @description List all chat threads, most recent first
   */
  list_threads_threads_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
    };
  };
  /**
   * Create Thread
   * @description Create a new chat thread
   */
  create_thread_threads_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateThreadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ThreadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete All Threads
   * @description Delete all chat threads and messages
   */
  delete_all_threads_threads_delete: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /**
   * Delete Thread
   * @description Delete a chat thread and all its messages
   */
  delete_thread_threads__thread_id__delete: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Thread
   * @description Update a chat thread's metadata
   */
  update_thread_threads__thread_id__patch: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateThreadRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Messages
   * @description List all messages for a thread, ordered by creation time
   */
  list_messages_threads__thread_id__messages_get: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatMessageModel"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Save Message
   * @description Save a new message to a thread
   */
  save_message_threads__thread_id__messages_post: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ChatMessageModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Message
   * @description Update an existing message (e.g., after streaming completes)
   */
  update_message_threads__thread_id__messages__message_id__patch: {
    parameters: {
      path: {
        thread_id: string;
        message_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatMessageModel"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bulk Import
   * @description Import threads and messages from localStorage in bulk
   */
  bulk_import_threads_import_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
